INSERT INTO province (name, slug) VALUES
('Azua', 'azua'),
('Bahoruco', 'bahoruco'),
('Barahona', 'barahona'),
('Dajabón', 'dajabon'),
('Distrito Nacional', 'distrito-nacional'),
('Duarte', 'duarte'),
('El Seibo', 'el-seibo'),
('Elias Piña', 'elias-pina'),
('Espaillat', 'espaillat'),
('Hato Mayor', 'hato-mayor'),
('Hermanas Mirabal', 'hermanas-mirabal'),
('Independencia', 'independencia'),
('La Altagracia', 'la-altagracia'),
('La Romana', 'la-romana'),
('La Vega', 'la-vega'),
('María Trinidad Sanchez', 'maria-trinidad-sanchez'),
('Monseñor Nouel', 'monsenor-nouel'),
('Monte Plata', 'monte-plata'),
('Montecristi', 'montecristi'),
('Pedernale', 'pedernale'),
('Peravia', 'peravia'),
('Puerto Plata', 'puerto-plata'),
('Samana', 'samana'),
('San Cristobal', 'san-cristobal'),
('San Jose de Ocoa', 'san-jose-de-ocoa'),
('San Juan', 'san-juan'),
('San Pedro de Macoris', 'san-pedro-de-macorís'),
('Sanchez Ramirez', 'sanchez-ramirez'),
('Santiago', 'santiago'),
('Santiago Rodriguez', 'santiago-rodriguez'),
('Santo Domingo', 'santo-domingo'),
('Valverde', 'valverde');

